import java.util.Optional;

public class OptionalDemo {
    public static void main(String[] args) {
        createOptionalExample();
        checkValueExample();
        getOrDefaultExample();
        ifPresentExample();
        mapAndFlatMapExample();
        filterExample();
        orElseChainExample();
    }

    // 1. 创建Optional对象
    public static void createOptionalExample() {
        System.out.println("=== 创建Optional ===");
        
        Optional<String> empty = Optional.empty();
        System.out.println("空的Optional: " + empty);
        
        Optional<String> present = Optional.of("Hello");
        System.out.println("非空Optional: " + present);
        
        String nullableValue = null;
        Optional<String> optionalNullable = Optional.ofNullable(nullableValue);
        System.out.println("可能为null的Optional: " + optionalNullable);
        
        String nonNullValue = "World";
        Optional<String> optionalNonNull = Optional.ofNullable(nonNullValue);
        System.out.println("非null值的Optional: " + optionalNonNull);
    }

    // 2. 检查值是否存在
    public static void checkValueExample() {
        System.out.println("\n=== 检查值是否存在 ===");
        
        Optional<String> present = Optional.of("Hello");
        System.out.println("isPresent: " + present.isPresent());
        System.out.println("isEmpty: " + present.isEmpty());
        
        Optional<String> empty = Optional.empty();
        System.out.println("isPresent (empty): " + empty.isPresent());
        System.out.println("isEmpty (empty): " + empty.isEmpty());
    }

    // 3. 获取值或默认值
    public static void getOrDefaultExample() {
        System.out.println("\n=== 获取值或默认值 ===");
        
        Optional<String> present = Optional.of("Hello");
        System.out.println("orElse: " + present.orElse("Default"));
        System.out.println("get: " + present.get());
        
        Optional<String> empty = Optional.empty();
        System.out.println("orElse (empty): " + empty.orElse("Default Value"));
        
        String result = empty.orElseGet(() -> "Generated by Supplier");
        System.out.println("orElseGet: " + result);
        
        try {
            empty.orElseThrow(() -> new RuntimeException("值不存在!"));
        } catch (RuntimeException e) {
            System.out.println("orElseThrow: " + e.getMessage());
        }
    }

    // 4. ifPresent和ifPresentOrElse
    public static void ifPresentExample() {
        System.out.println("\n=== ifPresent示例 ===");
        
        Optional<String> present = Optional.of("Hello World");
        present.ifPresent(value -> System.out.println("值存在: " + value));
        
        Optional<String> empty = Optional.empty();
        empty.ifPresent(value -> System.out.println("这行不会打印"));
        
        present.ifPresentOrElse(
                value -> System.out.println("值存在: " + value),
                () -> System.out.println("值为空")
        );
        
        empty.ifPresentOrElse(
                value -> System.out.println("值存在: " + value),
                () -> System.out.println("值为空，执行备选操作")
        );
    }

    // 5. map和flatMap转换
    public static void mapAndFlatMapExample() {
        System.out.println("\n=== map和flatMap ===");
        
        Optional<String> name = Optional.of("alice");
        Optional<String> upperName = name.map(String::toUpperCase);
        System.out.println("map转大写: " + upperName.orElse(""));
        
        Optional<Integer> length = name.map(String::length);
        System.out.println("map获取长度: " + length.orElse(0));
        
        Optional<User> user = Optional.of(new User("Alice", "alice@example.com"));
        Optional<String> email = user.map(User::getEmail);
        System.out.println("map获取邮箱: " + email.orElse("no-email"));
        
        Optional<String> emailUpper = user.flatMap(u -> Optional.ofNullable(u.getEmail()))
                .map(String::toUpperCase);
        System.out.println("flatMap+map: " + emailUpper.orElse(""));
        
        Optional<User> emptyUser = Optional.empty();
        Optional<String> emptyEmail = emptyUser.map(User::getEmail);
        System.out.println("空对象的map: " + emptyEmail.orElse("N/A"));
    }

    // 6. filter过滤
    public static void filterExample() {
        System.out.println("\n=== filter过滤 ===");
        
        Optional<String> email = Optional.of("alice@example.com");
        Optional<String> validEmail = email.filter(e -> e.contains("@"));
        System.out.println("有效邮箱: " + validEmail.orElse("无效邮箱"));
        
        Optional<String> invalidEmail = Optional.of("invalid-email");
        Optional<String> filtered = invalidEmail.filter(e -> e.contains("@"));
        System.out.println("无效邮箱: " + filtered.orElse("无效邮箱"));
        
        Optional<User> user = Optional.of(new User("Alice", "alice@example.com"));
        Optional<User> adultUser = user.filter(u -> u.getName().length() > 2);
        System.out.println("符合条件的用户: " + adultUser.map(User::getName).orElse("无"));
    }

    // 7. Optional链式调用
    public static void orElseChainExample() {
        System.out.println("\n=== 链式调用 ===");
        
        String result = Optional.ofNullable(getNullableValue())
                .map(String::toUpperCase)
                .filter(s -> s.length() > 3)
                .orElse("DEFAULT");
        System.out.println("链式调用结果: " + result);
        
        String nullResult = Optional.<String>ofNullable(null)
                .map(String::toUpperCase)
                .filter(s -> s.length() > 3)
                .orElse("Fallback Value");
        System.out.println("null处理结果: " + nullResult);
        
        User user = findUserById(1);
        String userEmail = Optional.ofNullable(user)
                .map(User::getEmail)
                .map(String::toLowerCase)
                .orElse("default@example.com");
        System.out.println("用户邮箱: " + userEmail);
    }

    // 辅助方法
    private static String getNullableValue() {
        return "hello";
    }

    private static User findUserById(int id) {
        if (id == 1) {
            return new User("Bob", "bob@test.com");
        }
        return null;
    }

    // 内部类
    static class User {
        private String name;
        private String email;

        public User(String name, String email) {
            this.name = name;
            this.email = email;
        }

        public String getName() {
            return name;
        }

        public String getEmail() {
            return email;
        }
    }
}
